# mostly from https://github.com/marketplace/actions/build-and-push-docker-images
name: Build and push image

on:
  pull_request:
    types:
      - closed

env:
  FS_IMAGE: ghcr.io/${{ github.repository }}
  FS_TAG: pr-${{ github.event.pull_request.number }}

jobs:
  docker:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Delete image, if it exists
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          tag: ${{ env.FS_TAG }}
          owner: ${{ github.repository_owner }}
          name: ftpsync
          token: ${{ secrets.GITHUB_TOKEN }}
