# mostly from https://github.com/marketplace/actions/build-and-push-docker-images
name: Delete temporary PR image

on:
  pull_request:
    types:
      - closed

env:
  FS_IMAGE: ghcr.io/${{ github.repository }}
  FS_TAG: pr-${{ github.event.pull_request.number }}

jobs:
  docker:
    runs-on: ubuntu-22.04

    # should match env.FS_TAG, in both pr-open.yaml and pr-close.yaml
    concurrency: pr-${{ github.event.pull_request.number }}

    permissions:
      packages: write
      pull-requests: write

    steps:
      - name: Delete image, if it exists
        uses: chipkent/action-cleanup-package@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-name: ${{ github.event.repository.name }}
          tag: ${{ env.FS_TAG }}

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Temporary image deleted.

      - name: Delete all images without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          repository_owner: ${{ github.repository_owner }}
          package_name: ftpsync
          untagged_only: true
          owner_type: user
