# mostly from https://github.com/marketplace/actions/build-and-push-docker-images
name: Build and push image

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  FS_IMAGE: ttl.sh/${{ github.repository }}/pr-${{ github.event.pull_request.number }}
  FS_TAG: 24h

jobs:
  docker:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-image
        with:
          image: ${{ env.FS_IMAGE }}
          tag: ${{ env.FS_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
