# mostly from https://github.com/marketplace/actions/build-and-push-docker-images
name: Build and push container

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: wistia/parse-tool-versions@v1.0

      - uses: earthly/actions/setup-earthly@v1
        with: { version: "v${{ env.EARTHLY_TOOL_VERSION }}" }

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extract tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: |
          earthly \
            --push \
            +image \
              --image=ghcr.io/djeebus/ftpsync:${{ env.RELEASE_VERSION }} \
              --GOLANG_VERSION=${{ env.GOLANG_TOOL_VERSION }}
