# mostly from https://github.com/marketplace/actions/build-and-push-docker-images
name: Update 'main' image

on:
  push:
    branches:
      - main

env:
  FS_IMAGE: ghcr.io/${{ github.repository }}
  FS_TAG: main

jobs:
  docker:
    runs-on: self-hosted

    concurrency: main

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-image
        with:
          image: ${{ env.FS_IMAGE }}
          tag: ${{ env.FS_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
