# mostly from https://github.com/marketplace/actions/build-and-push-docker-images
name: Build and push image

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  FS_IMAGE: ghcr.io/${{ github.repository }}
  FS_TAG: ${{ github.event.release.tag_name }}

jobs:
  docker:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-image
        with:
          image: ${{ env.FS_IMAGE }}
          tag: ${{ env.FS_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
